Renderers/src/artofillusion/raytracer/RaytracerRenderer.java

The SurfaceIntersection object provided to spawnRay()
may be recycled during call to getDirectLight()
Moved assigenment of hitObject to as soon as there is a
valid object to assign.

Keep reference to currently intersected object resolves #2

---

ArtOfIllusion/src/artofillusion.properties
ArtOfIllusion/src/artofillusion/ui/ImageFileChooser.java
ArtOfIllusion/src/artofillusion_fi.properties

Changes:
- Removed tif
- Removed svgz -- Needs unzipping, which is not provided by `SVGImage` constructors.
- Added  gif
- Added more  jpeg-type extensios
- Could not verify if pic-format is really supported _(did not find any pic-images)_, but I left it there because it was in `ImageMap.loadImage()` in the same block with hdr.

ImageFileChooser to match read-supported file types

---

ArtOfIllusion/src/artofillusion/ApplicationPreferences.java

#30 changed this from `Exception` to `NumberFormatException`, which meant that if any other type of exception was thrown, it wouldn't be caught.  Most importantly, if a preference simply isn't present (because you've just upgraded from an older version), it throws a `NullPointerException`.  This is a case where it's safest to just catch all exceptions, since returning the default value is always the best we can do in that case.

Catch exceptions for missing properties

---

ArtOfIllusion/src/artofillusion/animation/distortion/ShatterDistortion.java
ArtOfIllusion/src/artofillusion/object/TriangleMesh.java

This is my proposal for a fix to the problem, that a Shatter track freezes textured views at the point where a shattered object is set to disappear.
Two files were edited and either one of these changes would fix the problem alone. However, I chose to include both of modifications. They are actually addressed to different sides of the issue. Short comments added into the files.

A fix to Shatter track freezing textured views

---

ArtOfIllusion/src/artofillusion/view/SoftwareCanvasDrawer.java

This was the rootcause of camera views sometimes going blank.
To repeat the bug on on 3.0.3:
- Make sure you are using the `SoftwareCanvasDrawer`
- Open a new scene. Don't move or rotate views.
- Draw something on the scene for reference (and select it).
- Switch to 3D-manipulator.
- Select Camera 1 on the item list.

Division by zero-bug fixed

---

ArtOfIllusion/src/artofillusion/LayoutWindow.java

With Java 1.8.0_144 on Mac OS 10.12.6, the window briefly appears full size, but then immediately shrinks down to almost nothing.  I don't know why this fixes it, but it will do as a workaround.  See https://sourceforge.net/p/aoi/discussion/47784/thread/df034b7c/?limit=25#66b6 for more details.

Workaround for bug on Mac

---

ArtOfIllusion/src/artofillusion/LayoutWindow.java

This simplification from 3.0.3 causes an error if objects have parent/child relations in the object tree and new objects no longer appear in the object list.
The assumption has been, that the lenght of the object tree would be equal to number of objects in the scene. However this is true only as long as all objects are in the root level of the object tree. Otherwise the length of the object tree is the number of the stand-alone parent objects.
This modification changes the method to, what it is in 3.0.3.
_I don't remember, that I would have done this change myself, but I just as well might have...._

Bug fix to an 'addObject()'-simplification

---

ArtOfIllusion/src/artofillusion/image/ImagesDialog.java

Fixed the button issue and added follow up to the selected image at purge. Left the multiple load interrupt at error as it is with a comment in the file.
The reason I left the the interrupting there is, that if the user _(myself, as it happened_) accidentally tries to load a folder full of files that are not image files there is no way of interrupting the process otherwise. Probably the best way to handle that would be just to load the files, that can be loaded and notify afterwards about the failed ones. That change could be made as a separate PR though.
-P-

Fix #49, Image buttons @ purge

---

ArtOfIllusion/src/artofillusion/view/ViewerOrientationControl.java

This fixes the problem with the Orientation menu, that if there are several cameras with the same name in the scene, the first on the list one always gets selected, which ever the user tries to select.
Also discussed here https://sourceforge.net/p/aoi/discussion/47784/thread/8ba666ec/

Fix to View Orietation menu when several cameras have the same name.

---

ArtOfIllusion/src/artofillusion/Camera.java
ArtOfIllusion/src/artofillusion/SceneViewer.java

This fixes the problem that Konrad reported on SourceForge. 
The bug was, that the views could go blank, when you pressd and dragged on a view, that was set to perspective viewing. The cause was, that an object that was in the same location as then view camera could be selected at mouse press and then moved by drag, which caused an uncaught error in `findDragVector()` of `Camera`.
It is still possible to select a "wrong object" using the object list, but this fix deselects those when the illegal move is attempted.
I have not tested object editors for a similar case, but I believe the same phenomenon to be present there as well, though less likely to happen.

Fix to blank view on mouse drag in SceneViewer

---

ArtOfIllusion/src/artofillusion/image/MIPMappedImage.java

Was not initializing the SoftReferences, when a MIPMappedImage was created form an image in the memory (the LotteryBall script does that).
The effect was, that preview images could not be created and therefore the images dialog was unusable before save/open, when a MIPMap was created "online". Nothing was damaged though.

Fix to uninitialized SoftReferences

---

ArtOfIllusion/src/artofillusion/CameraFilterDialog.java
ArtOfIllusion/src/artofillusion/LayoutWindow.java
ArtOfIllusion/src/artofillusion/TexturesAndMaterialsDialog.java
ArtOfIllusion/src/artofillusion/image/ImageDetailsDialog.java
ArtOfIllusion/src/artofillusion/image/ImageOrColor.java
ArtOfIllusion/src/artofillusion/image/ImageOrValue.java
ArtOfIllusion/src/artofillusion/image/ImagesDialog.java
ArtOfIllusion/src/artofillusion/material/Material.java
ArtOfIllusion/src/artofillusion/material/ProceduralMaterial3D.java
ArtOfIllusion/src/artofillusion/material/UniformMaterial.java
ArtOfIllusion/src/artofillusion/object/DirectionalLight.java
ArtOfIllusion/src/artofillusion/object/PointLight.java
ArtOfIllusion/src/artofillusion/object/SceneCamera.java
ArtOfIllusion/src/artofillusion/object/SpotLight.java
ArtOfIllusion/src/artofillusion/procedural/SpectrumModule.java
ArtOfIllusion/src/artofillusion/texture/ImageMapTexture.java
ArtOfIllusion/src/artofillusion/texture/LayeredTexture.java
ArtOfIllusion/src/artofillusion/texture/ProceduralTexture2D.java
ArtOfIllusion/src/artofillusion/texture/ProceduralTexture3D.java
ArtOfIllusion/src/artofillusion/texture/Texture.java
ArtOfIllusion/src/artofillusion/texture/UniformTexture.java
ArtOfIllusion/src/artofillusion/ui/ColorChooser.java
ArtOfIllusion/src/artofillusion/ui/PropertyEditor.java

In lots of places we were passing the top level window as the parent for dialogs, instead of the dialog they were opened from.  This caused lots of problems when using Oracle Java on Mac, including dialogs appearing in back of other windows and UI events being missed.
This goes a long way toward making it usable with Java 8 on Mac.  There probably are other cases of this I've missed.  We'll need to keep an eye out for them and fix them as they come up.

Use correct parent when creating dialogs

---

ArtOfIllusion/src/artofillusion/RotateViewTool.java

This basically resumes two methods of the state they were in before the Java-9 adaptation. Nothing is new. The latter commit presents the exact same logic in a more conventional form.
Both commits have been tested both on Java 8 and Java 11.

Restoring pan/rotate switch

---

ArtOfIllusion/src/artofillusion.properties
ArtOfIllusion/src/artofillusion/ApplicationPreferences.java
ArtOfIllusion/src/artofillusion/CurveViewer.java
ArtOfIllusion/src/artofillusion/MaterialPreviewer.java
ArtOfIllusion/src/artofillusion/MeshViewer.java
ArtOfIllusion/src/artofillusion/MoveViewTool.java
ArtOfIllusion/src/artofillusion/ObjectPreviewCanvas.java
ArtOfIllusion/src/artofillusion/ObjectViewer.java
ArtOfIllusion/src/artofillusion/PreferencesWindow.java
ArtOfIllusion/src/artofillusion/RotateViewTool.java
ArtOfIllusion/src/artofillusion/SceneViewer.java
ArtOfIllusion/src/artofillusion/ScrollViewTool.java
ArtOfIllusion/src/artofillusion/SplineMeshViewer.java
ArtOfIllusion/src/artofillusion/TriMeshViewer.java
ArtOfIllusion/src/artofillusion/ViewerCanvas.java
ArtOfIllusion/src/artofillusion/animation/TrackGraph.java
ArtOfIllusion/src/artofillusion/animation/TracksPanel.java
ArtOfIllusion/src/artofillusion/object/DirectionalLight.java
ArtOfIllusion/src/artofillusion/object/SceneCamera.java
ArtOfIllusion/src/artofillusion/object/SpotLight.java
ArtOfIllusion/src/artofillusion/texture/UVMappingViewer.java
ArtOfIllusion/src/artofillusion/ui/TreeList.java
ArtOfIllusion/src/artofillusion/ui/UIUtilities.java
ArtOfIllusion/src/artofillusion/view/ViewAnimation.java
ArtOfIllusion/src/artofillusion/view/ViewerPerspectiveControl.java
ArtOfIllusion/src/artofillusion_fi.properties

Hi everybody! 
I call this one done. This \<edit\>is a response to\</edit\> #64 at least partially. And in spite of the branch name it is a bit more than just a graphics update.
Splitting this into several PRs would not have worked as all the commits rely on the earlier ones and I really had to start from the basics (befc7a7, which I should have done in the first place). After attempting a few work-arounds this produced the cleanest out come without methods just to fight the core logic.
- View cameras behave better now and you can continue where you left off after save and reopen -- they remember their last working depth in the view.
- SceneCamera perspective setting overrides the view perspective setting.
- Children of  camera objects should now follow their parent in animated moves …

View manipulation & graphics update and bug fix

---

ArtOfIllusion/src/artofillusion/LayoutWindow.java

First part of  #31.
Two things were wrong:
- The command was in the wrong block
- Visibility was recognized by the size of `itemTreeScroller` _(width or height == 0)_. However the size of the element itself was not changing, when the split-bar was forced to the edge. --> It was thought always to be shown. Now there is a boolean to remember the user's choice. _(Maybe not the ultimate clever solution, but works for now.)_
The command only applies to the panel, that the object list is part of and if the list is afloat, the command does nothing.
EDIT:
> the size of the element was not changing
The visibility of the score is detected the same way and that one works.

ObjectList hide/show fix

---

ArtOfIllusion/src/artofillusion/ArtOfIllusion.java

@peastman It's been a while since I saw any issues with tooltip z-order on Windows or Linux.
I suspect that Newer JVMs may have improved their handling in this respect. Could you check with a Mac? Might this also have been related to the window parenting issue?
I'd leave it in place, but the more recent, more aggressive deprecation/removal policies make it likely that we will need to deal with this sooner or later. Thoughts/feedback appreciated.

Fix Illegal reflection - ToolTips

---

ArtOfIllusion/src/artofillusion/view/ViewerNavigationControl.java

Removing a sick method. It was never called, so it did not cause any issues but it definitely should not be there.
I have no idea how that got there, but the most likely scenario I can think of is, that it was a left-over line from something else and I just patched without thinking to get it through the compiler  ... and then forgot.

Bad method removal

---

ArtOfIllusion/src/artofillusion/animation/SkeletonTool.java

The creation depth of the root bone was wrong. After this it is the working depth of the view as expected. Works correctly both in parallel an perspective modes.
This seems to have slipped through my fingers in the views update.
- Bug fix. 
- Target 3.1.1

Creation depth of RootJoint corrected

---

ArtOfIllusion/src/artofillusion/view/GLCanvasDrawer.java

Handling a bug in GL/Nvidia/Win10 environment that caused Java to crash. This is by no means a "fix" to the bug, that is outside our reach. This just prevents the unhandled error from happening by setting some initial values to an entity that the Nvidia drivers seem to expect to find.
Changes of #143 are included here, but this branch is derived from the master.
**Target 3.1.1**

NVIDIA crash bug tackle

---

ArtOfIllusion/src/artofillusion/ObjectViewer.java
ArtOfIllusion/src/artofillusion/TriMeshViewer.java
ArtOfIllusion/src/artofillusion/ViewerCanvas.java
ArtOfIllusion/src/artofillusion/view/ClickedPointFinder.java

Resolves  #148 on AoI side. PolyMeshViewer can be updated later if necessary.
I tested doing just 
~~~~java
if (v instanceof TriMeshViewer)
hideFace = ((TriMeshEditorWindow)((TriMeshViewer)v).getController()).getHiddenFaces();
~~~~
in the ClickedPointFinder, but it does not look like good practice to me and it would limit the effect to TriangleMeshes only. Done the way it is now in the PR, it allows adding new object types without having to add each one of them individually to CPF.

Center click to see through hidden faces

---

ArtOfIllusion/src/artofillusion/MoveScaleRotateMeshTool.java
ArtOfIllusion/src/artofillusion/MoveScaleRotateObjectTool.java
ArtOfIllusion/src/artofillusion/ui/Compound3DManipulator.java

Here are some improvements to the Compound3DManipulator.
- Handle distance to the axes stays constant regardless of the size of the manipulator
- UV-directions are now U to right and V up
- NPQ mode renamed PQN mode. _The N stands for normal in model coordinates and object-Z in scene._
- In parallel viewing the move follows the handle correctly also, when there is depth movement included.
- In perspective mode the move and the manipulator tend to get ahead or be left behind of the mouse depending on the relative direction. To have it precisely follow the mouse looks like a very complex process. _(I tested a bit but I'm literally back at the drawing board with it)_
- <strike>In perspective mode it is not a 100% success otherwise either but hopefully better than before.</strike> Actually it …

3D-Manipulator improvements

---

ArtOfIllusion/src/artofillusion/MoveViewTool.java
ArtOfIllusion/src/artofillusion/ScrollViewTool.java
ArtOfIllusion/src/artofillusion/ViewerCanvas.java
ArtOfIllusion/src/artofillusion/view/ViewerScaleControl.java

This prevents zooming into "crash zone".
`Fit View to Selection` selection, when the selected object(s) return a zero-sized bounding box would blank the view. Now the minimum distance from Camera to drawing plane is set to 1.0E-12.  Surprisingly with this magnification and the view set to parallel mode you can still create primitives and rotate the view normally. Some display modes (transparent and shaded) don't work correctly any more though.
The limit is set to the scroll wheel zoom and the magnification field of the ViewerCanvas. It is _possible_ to scroll wheel to 1.0E-12 distance of a point (= 2.0E15 scaling) but it _does_ take some patience....

Minimum zoom distance

---

docs/manual/conf.py

This I kind of feel strongly about, no matter what other decisions we make regarding templates, formatting, etc:
The sidebar should have a global toc! I want to see what my options are in whatever I'm reading!

Change to full TOC in manual sidebar

---

docs/manual/rendering.rst

I noticed these strange instructions in the Rendering section.
I don't know what the relevance of that would have been in using the rendering dialog in the first place and even stranger, what the setting zoom to 100 had to do with anything: Would you not have liked to preview the camera as it was set? With the current code that would not even work.

Removing a confusing instruction

---

ArtOfIllusion.xml
OSSpecific.xml
Renderers.xml
Tools.xml
Translators.xml
build.properties
build.xml

Should have done this the last time I messed about with the build files... can't remember why not.
Makes updating defaults much easier, and can still over-ride on the command line if needed.

Refactor build definition to use global properties

---

ArtOfIllusion/src/keystrokes.xml

In the early versions of AoI delete was under Delete key as you would expect. At some point it was moved to the Backspace-key, which still after all the years is confusing to me and I believe to most users anyway....
This PR adds the function back to Delete-key as well. There's nothing wrong with using BS for the same purpose but a dedicated key, that ROW uses, should not be blank.
..So now it would be much like any text processor. Either Del or BS will delete the current selection.

Reconnect delete-key

---

ArtOfIllusion/src/artofillusion/Scene.java

Save `ObjectInfo.locked` status to disk with the scene.
Contains a format change. Target release 3.2
Resolves #178

objectinfo lock to be saved

---

ArtOfIllusion/src/artofillusion/procedural/BrickModule.java
ArtOfIllusion/src/artofillusion/procedural/CellsModule.java
ArtOfIllusion/src/artofillusion/procedural/ClipModule.java
ArtOfIllusion/src/artofillusion/procedural/ColorModule.java
ArtOfIllusion/src/artofillusion/procedural/CommentModule.java
ArtOfIllusion/src/artofillusion/procedural/CoordinateModule.java
ArtOfIllusion/src/artofillusion/procedural/ExprModule.java
ArtOfIllusion/src/artofillusion/procedural/FunctionModule.java
ArtOfIllusion/src/artofillusion/procedural/GridModule.java
ArtOfIllusion/src/artofillusion/procedural/ImageModule.java
ArtOfIllusion/src/artofillusion/procedural/JitterModule.java
ArtOfIllusion/src/artofillusion/procedural/MarbleModule.java
ArtOfIllusion/src/artofillusion/procedural/NoiseModule.java
ArtOfIllusion/src/artofillusion/procedural/NumberModule.java
ArtOfIllusion/src/artofillusion/procedural/ParameterModule.java
ArtOfIllusion/src/artofillusion/procedural/RandomModule.java
ArtOfIllusion/src/artofillusion/procedural/ScaleShiftModule.java
ArtOfIllusion/src/artofillusion/procedural/SpectrumModule.java
ArtOfIllusion/src/artofillusion/procedural/TransformModule.java
ArtOfIllusion/src/artofillusion/procedural/TurbulenceModule.java
ArtOfIllusion/src/artofillusion/procedural/ViewAngleModule.java
ArtOfIllusion/src/artofillusion/procedural/WoodModule.java

Update procedural module's duplicate() method declaration to be more specific. This reduces dependencies count of deprecated Module class

Update module duplicate result type

---

ArtOfIllusion/src/artofillusion/ViewerCanvas.java

I have noticed, when playing wit zoom, center click, perspective etc... that sometimes the view is not responding the way I expected but I could not exacty tell where it went wrong and the problem always seemed to fix itself by the following view manipulation actions.
Now I found it! 
This makes sure that changing from parallel to perspective keeps screen dimensions unchanged at working depth, after you have selected a new point of focus by center click. This is the way it was originally supposed to be.

A bug fix to view manipulation

---

ArtOfIllusion/src/artofillusion/animation/Joint.java

Addressing a long term bug in creation of new bones.
The "twist" angle is in principle calculated correctly from the various directions and coordinates that are involved but often the resulting angle is 180° or -180° instead of 0° (or for example -123° instead of 57°).
The near 180 degree angles prevent using angular restrictions and often force the movements to happen over the ±180° limit, which is a bit difficult to handle. A typical place to set limits to twist angle would be a spine structure, where each bone may be allowed to move only a few degrees. To add restrictions you'd have to turn the bone around but if the bone already has children, that usually is not a reasonable option. 
- This makes sure that the initial Z-rotation of a new bone is always between -90° and 90°.
- This …

initial twist angle

---

ArtOfIllusion/src/artofillusion/object/Cylinder.java

On the keyframe-editor of Cylinder Pose track the radii fields were set to display size, not radius. The fields were called 'Bottom Radius (X)' and '-(Z)' though.
I have sometimes though that there something seemed funny about how cylinder behave, but this was it. The object editor is displaying the radii as it should.

Bug fix to Cylinder pose track keyframe editor

---

Tests/src/artofillusion/object/ImplicitSphereTest.java

As discussed in #67 
Well, this took me down a deeper rabbit hole than I was expecting. I've done the following:
- Restructured pretty much the entire test class.
+ I broke the various tests out into separate test methods, to improve localizing any failures. The test case name should tell exactly what kind of unexpected we've run into.
+ Added a readable printout of the <sphere, point> pair that failed the test
+ This would be much easier if we had a property testing framework (plugin to junit 5, but I'm not going there right now)
- Fixed two separate false failure modes, both as expected from the issue discussion
+ Scaled the allowable delta between the estimated and returned gradients proportional to the returned gradient
+ At the edge of the influence radius, some of the samples for …

Harden test implicit resolves #67

---

ArtOfIllusion.xml
ArtOfIllusion/src/artofillusion/ArtOfIllusion.java
ArtOfIllusion/src/artofillusion/TitleWindow.java
build.xml

Automatically include Git commit data in `META-INF/MANIFEST.MF`
The intent is to make it possible to tell *Exactly* what version of AOI is being run, especially when troubleshooting for our users.
This takes the form of a string formatted as follows:
`<Latest Tag in the main branch>-<Commits since Tag>-<Current Commit Hash>-<Optional "dirty" flag if there are uncommitted changes>`
If built from a source-zip or in a non-standard way (not through the ANT script), a message about missing source version will be included instead.
I've displayed this data in the Title Window on startup, but it should be easily accessible from scripts, loggers, etc.

Include commit identifier when building

---

ArtOfIllusion/src/artofillusion/animation/Joint.java

The problem is demonstrated in the zipped .mp4 below. 
[twisanglefixbug.zip](https://github.com/ArtOfIllusion/ArtOfIllusion/files/5286776/twisanglefixbug.zip)
I should have realized that after modifying the angle the CoordinateSystem system needs to be recalculated. Otherwise the outdated CoordinateSystem takes over the next time the bones move.

twist angle optimization recoded

---

Renderers/src/artofillusion/raytracer/RaytracerRenderer.java

The Illumination tab had all input fields enabled at start-up. Also after re-opening a file the enabled-states were not necessarily up to date. Added `dipatchEvent`s just like to the General tab, to update it at launch.

Illumination tab initial enabled-status

---

ArtOfIllusion/src/artofillusion/LayoutWindow.java

The Save-menuItem was staying enabled after save, if you didn't at least click a view after saving (by "Save"). Most actions on the UI `updateMenus()` but his did not.
There seems to be something not quite right with the Move and Rotate tools too that the `menuItem` does always get updated. If this PR is still here when I come up with a fix to those I'll add it here. If not, I'll PR that separately.

Save menu item enabled state

---

ArtOfIllusion/src/artofillusion/PluginRegistry.java

I try to install GLRenderer plugin with SPManager. 
Once application is restarted it stuck on showing TitleWindow.
I see NoClassDefFoundError as this plugin expected classes from old JOGL

Catch for NoClasDefFoundError

---

Renderers/src/artofillusion/raytracer/RTCube.java
Renderers/src/artofillusion/raytracer/RTCylinder.java
Renderers/src/artofillusion/raytracer/RTEllipsoid.java
Renderers/src/artofillusion/raytracer/RTSphere.java
Renderers/src/artofillusion/raytracer/RTTriangle.java
Renderers/src/artofillusion/raytracer/RTTriangleLowMemory.java

The light ray issue fix for actual primitives, `Sphere`, `Ellipsoid`, `Cube` and `Cylinder`.
I think the solution is now simpler than before. No fields needes to be and only one variable in one method.
I tested `Math.max/min` vs. `if( < > )` with a plugin. It turned out that the `max` and `min` functions in real Java (as in comparison to Groovy) are faster than `if`. It is hard to say exactly how much faster as results in Windows vary quite a bit, but significantly. For comparison I added a set of multiplying and dividing to the test set. The `max` and `min` seem to be speed wise just as good a those. 
I may have a look at `RTTriangle` too and add it to this if I can get the implementation simplified and also see what, if anything, to do with `RTImplicitObject`.

Rendering primitives, Light ray fix

---

ArtOfIllusion/src/artofillusion/ArtOfIllusion.java

Workaround for a (weird) timing issue when disposing of GLJPanels on (some) macs. This should hold until the underlying issue is fixed in the JOGL libraries.
Needs testing on windows.

Dispose of unmodified windows after delay courtesy of Runic

---

ArtOfIllusion/src/artofillusion/ViewerCanvas.java

Clicking on ObjectPreview canvas inside Tools dialogs trows NPE into log because of no animator set for this views

Avoid NPE from Canvas

---

ArtOfIllusion/src/artofillusion/script/GroovyScriptEngine.java

For now only groovy compilation exception wrapped with aoi ScriptException. 
But uncatched groovy runtime exception may prevent application to be started if thrown from startup script (this way I found such case)

Catch all groovy script exceptions

---

ArtOfIllusion/src/artofillusion/script/ExecuteScriptWindow.java

Fix IndexOutOfBounds exception when actual newRecentFiles list size less than hardcoded 10 value. Also removed unnesessary convert and cast to String array

Fix AIOB in ExecuteScript Window

---

ArtOfIllusion/src/artofillusion/ViewerCanvas.java
ArtOfIllusion/src/artofillusion/view/ViewAnimation.java

Fix to the disappearing grids issue mentioned [here](https://sourceforge.net/p/aoi/discussion/47783/thread/db8076ee17/). 
One way to could have been been to draw the grid always, when it is on. In many cases it would not hurt, but if there is a large move or a strong scaling happening, the flashing can be rather disturbing.
There were a couple of minor comment typo fixes in the last commit included, I hope those are not too disturbing. I could not just scroll past them when they hit my eye. :)

Grid timing
