- Building.md
- Contributing.md
- Readme.md
Added instructions on how to build AOI and what should go into
a pull request.
> Added some basic developer documentation

- ArtOfIllusion/src/artofillusion/LayoutWindow.java
Hi!
Added view menu to LayoutWindow. 
The DisplayModeIcons plugin works after this change. 
Not sure if I used GitHub as I was supposed to. If not, I'd be happy to try another time. :)
-P-
> View menu to Scene view

- ArtOfIllusion/src/artofillusion/ArtOfIllusion.java
> Refactoring: Convert plugin event calls to foreach style in main App class

- ArtOfIllusion/src/artofillusion/image/HDRImage.java
- ArtOfIllusion/src/artofillusion/image/ImagesDialog.java
- ArtOfIllusion/src/artofillusion/image/MIPMappedImage.java
- ArtOfIllusion/src/artofillusion/image/SVGImage.java
That's all I could thing about and the fix works for me. 
Induced by the user 'Helge-H' on SourceForge. https://sourceforge.net/p/aoi/discussion/47783/thread/2c90fc28/
> MIP-Mapped Image, grayscale losing data bug fix

- ArtOfIllusion/src/artofillusion/math/Vec3.java
Adding this method, that I have been missing.  Discussed on SF https://sourceforge.net/p/aoi/discussion/47784/thread/dd7c3020/
> Adding unit() to Vec3.

- ArtOfIllusion/src/artofillusion/math/Vec2.java
Working on the 3DManipulator I realized that I had forgotten Vec2, when I added unit() to Vec3, so here it is. :)
> Adding unit() to Vec2 too.

- ArtOfIllusion/src/artofillusion/LayoutWindow.java
- ArtOfIllusion/src/artofillusion/ListChangeListener.java
- ArtOfIllusion/src/artofillusion/ModellingTool.java
- ArtOfIllusion/src/artofillusion/Plugin.java
- ArtOfIllusion/src/artofillusion/Translator.java
- ArtOfIllusion/src/artofillusion/animation/Marker.java
- ArtOfIllusion/src/artofillusion/animation/TrackDisplay.java
- ArtOfIllusion/src/artofillusion/procedural/IOPort.java
- ArtOfIllusion/src/artofillusion/procedural/InfoBox.java
- ArtOfIllusion/src/artofillusion/procedural/Link.java
- ArtOfIllusion/src/artofillusion/procedural/PointInfo.java
- ArtOfIllusion/src/artofillusion/ui/FloatingDialog.java
- ArtOfIllusion/src/artofillusion/ui/TreeElement.java
- ArtOfIllusion/src/artofillusion/ui/ValueChecker.java
- Translators/src/artofillusion/translators/VRMLTranslator.java
Finish line ending conversions. Hopefully, this is the last of them. Apparently, many of the automated options are not 100% effective. Manually converted the rest
> Convert Remaining CR to LF

- ArtOfIllusion/src/artofillusion/view/GLCanvasDrawer.java
Fixes layout problems using Oracle Java on Mac.
> Use GLJPanel instead of GLCanvas

- ArtOfIllusion/src/artofillusion/LayoutWindow.java
- ArtOfIllusion/src/artofillusion/Scene.java
See https://sourceforge.net/p/aoi/feature-requests/384/
> Speed improvements when working with many objects

- ArtOfIllusion/src/artofillusion/view/GLCanvasDrawer.java
- ArtOfIllusion/src/artofillusion/view/TexturedVertexShader.java
Textured mode was slow because of the need to do a texture calculation for every vertex.  I had tried to address that by caching those texture calculations, but if an object had any per-face or per-face-vertex parameter, it skipped caching and repeated the calculation for every redraw.  I've now changed it so it can cache the textures in that case too, which makes it a lot faster.
I also changed the format in which it caches the information.  This reduces the memory used by the cache.
I also changed the OpenGL code used in that case to reduce the overhead.
> Improved speed of textured display mode

- ArtOfIllusion/src/artofillusion/LayoutWindow.java
- ArtOfIllusion/src/artofillusion/SceneViewer.java
- ArtOfIllusion/src/artofillusion/ScrollViewTool.java
- ArtOfIllusion/src/artofillusion/ViewerCanvas.java
- ArtOfIllusion/src/artofillusion/view/ViewAnimation.java
- ArtOfIllusion/src/artofillusion/view/ViewerNavigationControl.java
- ArtOfIllusion/src/artofillusion/view/ViewerPerspectiveControl.java
Cleaned-up version of #74, with whitespace changes removed.
> Navigation System Fixes - resolves #74

- ArtOfIllusion/src/artofillusion/PreferencesWindow.java
- ArtOfIllusion/src/artofillusion/ui/Translate.java
Once user's default locale is differs from registered and user has no stored options opening Properties window set selected language option to first registered one (It's africaanas). After that new windows are opens with this new language option.
I restrict Translate. setLocale to set only registered values. Otherwise set to US
> Update set and get app Locales. Restrict locale set to registered only.

- ArtOfIllusion/src/artofillusion/RenderingDialog.java
- ArtOfIllusion/src/artofillusion/animation/ObjectRefSelector.java
- ArtOfIllusion/src/artofillusion/image/ImageSaver.java
These are some more cases that caused incorrect behavior on macOS with Oracle Java.
> Fixed a few more cases of wrong parent being used for dialog

- ArtOfIllusion/src/artofillusion/ViewerCanvas.java
Scale had to be different in perspective and parallel.
> Fixing a small glitch in fit view to objects

- ArtOfIllusion/src/artofillusion/LayoutWindow.java
> Removing duplicate line.

- ArtOfIllusion/src/artofillusion/MoveViewTool.java
- ArtOfIllusion/src/artofillusion/RotateViewTool.java
- ArtOfIllusion/src/artofillusion/ScrollViewTool.java
Resolves #125
While I'm at it, I could add scroll wheel zoom to the previews too, if this is not merged first.
> Preview respond to mouse

- ArtOfIllusion/src/artofillusion.properties
- ArtOfIllusion/src/artofillusion/image/ImageDetailsDialog.java
- ArtOfIllusion/src/artofillusion_fi.properties
> Confirm imageconvert

- ArtOfIllusion/src/artofillusion/TriMeshBeveler.java
I also did a bit of code cleanup while I was at it, including replacing tabs with spaces.  Tell it not to show whitespace changes to get a better idea of what changed.
> Improved performance of beveling meshes

- Tools/src/artofillusion/tools/TextDialog.java
- Tools/src/artofillusion/tools/TextTool.java
> Normal direction of surface text

- ArtOfIllusion/src/artofillusion/ui/AutoScroller.java
> Fix NPE from autoscroller

- OSSpecific/src/artofillusion/osspecific/MacOSPlugin.java
This is a simpler alternative to #165.
> MacOSPlugin works with JDK9+

- ArtOfIllusion/src/artofillusion/MaterialMappingDialog.java
- ArtOfIllusion/src/artofillusion/Scene.java
- ArtOfIllusion/src/artofillusion/TextureMappingDialog.java
- ArtOfIllusion/src/artofillusion/animation/Actor.java
- ArtOfIllusion/src/artofillusion/animation/PoseTrack.java
- ArtOfIllusion/src/artofillusion/object/Object3D.java
- ArtOfIllusion/src/artofillusion/procedural/Module.java
- ArtOfIllusion/src/artofillusion/procedural/Procedure.java
- ArtOfIllusion/src/artofillusion/ui/ThemeManager.java
- Tests/src/artofillusion/procedural/ModuleTest.java
More array to varargs style call changes
> Update class lookup and instantiating with varargs style

- ArtOfIllusion/src/artofillusion/ViewerCanvas.java
Hi.
Renewed drawing of the coordinate axes on the views. The problems were the flickering and the misshaped labels, due to differences in the CanvasDrawers. I also gave up the idea of having the axes react to perspective setting. It probably was not intentional to begin with though a kind of cool, and definitely different from anywhere else. Now it is purely an orientation indicator.
The axes are now handled as an inner class. It did not seem reasonable to have the elements available to the rest of the word.
There is a public static variable to control the size. You can try
~~~~groovy
window.getView().coordinateAxisSize = 45;
~~~~
to test.
> Coordinate axes drawing

- ArtOfIllusion/src/artofillusion/ObjectSet.java
> ObjectSet save fixed

- build.properties
I think we settled this already... are there any last minute concerns?
> Update minimum supported java version

- ArtOfIllusion/src/artofillusion.properties
- ArtOfIllusion/src/artofillusion/animation/JointEditorDialog.java
- ArtOfIllusion/src/artofillusion_fi.properties
The DOF-editor as discussed. Closes #164. 
- Now the handles can be separated even if the opposing handles are on top of each others just by picking on the side that you wish to drag.
- The general "jumpiness" is tamed down a bit.
- The colors have dark/light contrast that should be sufficient even to reduced color vision. I avoided using direct green/red contrast.
EDIT: I'll try to see if I can reduce the size of the editor a bit as in it's current design it covers so much of the screen that you can not see the bones, that you are working on....
> Joint handling updates

- ArtOfIllusion/src/artofillusion/animation/PoseTrack.java
- ArtOfIllusion/src/artofillusion/animation/WeightTrack.java
Take in accоunt that Pose Track subtracks may be added from outside. Ex. Camera's filters parameters tracks
Original issue from Sourceforge thread: https://sourceforge.net/p/aoi/discussion/47783/thread/a299917f8b/
> Update Pose track duplicate/copy methods.

- ArtOfIllusion/src/artofillusion/Scene.java
+ Small update of code with modern style
> Made Scene textures and materials available as lists.

- Renderers/src/artofillusion/raytracer/RaytracerRenderer.java
As it says. Resolves #198.
I was a little bit worried about putting an `if()` inside a `for` inside another `for`. With some admittedly light testing the effect seems to be some 5-10% more time spent in the soft shadows method. _(Stdevs of the results are much higher than that, but the trend seems consistent.)_
Taking the `if` outside the `for-for` would lead to some restructuring of that method. Whether it'd be worth it, I'd be happy to hear what anybody else thinks? Not that big a job really, but AFAICT there might be a couple of different ways, how to do it.
> Soft rendering to truely comply with antialias selection

- Renderers/src/artofillusion/raytracer/RaytracerRenderer.java
Just a little something to hide the scroll bars that appeared to scroll just one item!
> hide antialiasing scrollbars

- ArtOfIllusion/src/artofillusion.properties
- ArtOfIllusion/src/artofillusion/RenderSetupDialog.java
- ArtOfIllusion/src/artofillusion_fi.properties
A somewhat surprising discovery... :/
> Translate 'Single Image' and 'Movie'

- ArtOfIllusion/src/artofillusion/RenderSetupDialog.java
Resolves #230.
Now it checks if settings have changed and if so call `setModified()`. An addition to the`Renderer` interface was needed get the information the renderers but it seems that renderers that have been compiled before the change would still work if they are otherwise compatible.
I came up with a kind of a hidden feature for cases where the user _(well myself at least)_ might like to save already changed settings on Cancel. Let me know what you think.
> Save RenderSetupDialog settings to metadata 

- ArtOfIllusion/src/artofillusion/RenderSetupDialog.java
A little _oops_ in the new bit. The rest seemed OK.
> StartTime of rendering Movie

- ArtOfIllusion/src/artofillusion/ui/ToolPalette.java
Avoid AIOB exception in log from Tool Palette when click on palette empty cell space
> Avoid AIOB exception in log from Tool Palette

- ArtOfIllusion/src/artofillusion/script/ExecuteScriptWindow.java
- ArtOfIllusion/src/artofillusion/script/ScriptedObjectEditorWindow.java
@peteihis brought this up when [discussing potential enhancements to the standard File Dialogs.](https://sourceforge.net/p/aoi/discussion/47782/thread/a8de70e03f/?limit=25#e112)
> Script load and Save don't affect file-search directory

- ArtOfIllusion/src/artofillusion/object/TriangleMesh.java
Update and clean up an absolutely ancient doc comment.
Does this look right?
> Correct Javadoc. Resolves #290

- ArtOfIllusion/src/artofillusion/keystroke/KeystrokeEditor.java
- ArtOfIllusion/src/artofillusion/script/ExecuteScriptWindow.java
- ArtOfIllusion/src/artofillusion/script/ScriptEditingWidget.java
- ArtOfIllusion/src/artofillusion/script/ScriptedObjectEditorWindow.java
- ArtOfIllusion/src/scriptEditorTheme.xml
Make sure that documentation-style comments are styled like other comments. I think these just got missed originally.
> unify styling of comment types

- ArtOfIllusion/src/artofillusion/script/ExecuteScriptWindow.java
Update renderer to properly render list items when hovered with mouse
> Update language selection renderer
